version: 2.1

jobs:
  test:
    docker:
      - image: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
